
services:
  server:
    build: .
    ports:
      - "80:80"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_PATH: "/server/database"
      DATA_SOURCE_DIR: "/server/data-sources"
    volumes:
      - /database:/server/database
      - /data-sources:/server/data-sources
  app:
    build: ./wa-chat
    ports: 
      - "5000:5000"
    